using Andrew Trask, Ian GoodFellow presentation 

![title](predict_compare.png)


![title](basic_neuralN.png)

In [29]:
#It multiplies the input by a weight. It "scales" the input by a certain amount
def neural_network(input, weight):
    prediction = input * weight
    return prediction

In [31]:
input = 0.82 # num. of toes
weight = 2

pred = neural_network(input,weight)
print(pred)

1.64


![title](basic_multipleinputs.png)


In [10]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def neural_network(input, weights):
    pred = w_sum(input,weights) #weighted sum or dot product 
    return pred


weights = [0.1, 0.2, 0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
# input corresponds to every entry
# for the first game of the season
input = [toes[0],wlrec[0],nfans[0]] # [8.5,0.65,1.2]

#[ 8.5*0.1 + 0.65*0.2 + 0 * 1.2]

pred = neural_network(input,weights)
print(pred)

0.98


In [11]:
import numpy as np

In [12]:
def neural_network(input, weights):
    pred = input.dot(weights) # dot product
    return pred

weight = np.array([0.1, 0.2, 0])

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
# input corresponds to every entry
# for the first game of the season

input = np.array([toes[0],wlrec[0],nfans[0]]) # [8.5,0.65,1.2]

pred = neural_network(input,weight)
print(pred)

0.98


Similarity Notion

![title](similarityNotion.png)

![title](neural1.png)

In [13]:
def neural_network(input, weights):
    pred = input.dot(weights) # dot product
    return pred

#weight = np.array([0.1, 0.2, 0])

                    #toes %win #fans
weights = np.array([ [0.1, 0.1, -0.3],#hurt?
                     [0.1, 0.2, 0.0], #win?
                     [0.0, 1.3, 0.1] ])#sad?

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
# input corresponds to every entry
# for the first game of the season

input = np.array([toes[0],wlrec[0],nfans[0]]) # [8.5,0.65,1.2]

pred = neural_network(input,weights)
print(pred)

[ 0.915  2.54  -2.43 ]


![title](multi_layer.png)

In [14]:
import numpy as np

                   #toes %win #fans
ih_wgt = np.array([[0.1, 0.2, -0.1],#hid[0]
                   [-0.1,0.1, 0.9], #hid[1]
                   [0.1, 0.4, 0.1]]).T #hid[2]

                   # hid[0] hid[1] hid[2]
hp_wgt = np.array([[0.3, 1.1, -0.3],#hurt?
                   [0.1, 0.2, 0.0], #win?
                   [0.0, 1.3, 0.1] ]).T#sad?




weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input,weights)
print pred

#  To predict, neural networks perform repeated weighted sums or dot product of the input.

[ 0.2135  0.145   0.5065]


## Compare
### A measurement of how much our prediction "missed".

![title](compare.png)

## Learn
### "Learning" takes our error and tells each weight how it can change to reduce it.

In [22]:
#Gradient Descent

weight = 0.5
goal_pred = 0.8
input = 0.5 #correct input = 0.5, incorrect input = 1000 (scale side efect)

for iteration in range(50):
    pred = input * weight
    error =  (pred - goal_pred) ** 2
    #error = (goal_pred -  pred) ** 2
     
    
    direction_and_amount = (pred - goal_pred) * input 
    #direction_and_amount = (goal_pred - pred) * -input 
    weight = weight - direction_and_amount # weight + ((-1)* direction_and_amount)
    
    print "Error:" + str(error) + " Prediction:" + str(pred)

# Learning is adjusting our weight to reduce the error to zero

Error:0.3025 Prediction:0.25
Error:0.17015625 Prediction:0.3875
Error:0.095712890625 Prediction:0.490625
Error:0.0538385009766 Prediction:0.56796875
Error:0.0302841567993 Prediction:0.6259765625
Error:0.0170348381996 Prediction:0.669482421875
Error:0.00958209648728 Prediction:0.702111816406
Error:0.0053899292741 Prediction:0.726583862305
Error:0.00303183521668 Prediction:0.744937896729
Error:0.00170540730938 Prediction:0.758703422546
Error:0.000959291611528 Prediction:0.76902756691
Error:0.000539601531484 Prediction:0.776770675182
Error:0.00030352586146 Prediction:0.782578006387
Error:0.000170733297071 Prediction:0.78693350479
Error:9.60374796025e-05 Prediction:0.790200128593
Error:5.40210822764e-05 Prediction:0.792650096444
Error:3.03868587805e-05 Prediction:0.794487572333
Error:1.7092608064e-05 Prediction:0.79586567925
Error:9.61459203602e-06 Prediction:0.796899259437
Error:5.40820802026e-06 Prediction:0.797674444578
Error:3.0421170114e-06 Prediction:0.798255833434
Error:1.7111908189

### The Secret

For any input and goal_pred, there is an exact relationship
defined between our error and weight, found by combining
our prediction and error formulas. In this case: <br>
error = (  pred - goal_pred) ^ 2 <br>
error = ( (input x weight) - goal_pred ) ^ 2 <br>
error = ( (0.5 x weight) - 0.8) ^ 2 <br>


![title](derivate_slope.png)

In [23]:
#gradient descent (values not vector or matrices)

weight = 0.5
goal_pred = 0.8
input = 10 # good input = 10, input = 1000
alpha = 0.0012 # learning rate  good alpha = 0.001 

for iteration in range(50):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    derivative = (pred - goal_pred) * input 
    
    weight = weight - (alpha * derivative) # EXPLAIN ALPHA
    
    print "Error:" + str(error) + " Prediction:" + str(pred)

Error:17.64 Prediction:5.0
Error:13.660416 Prediction:4.496
Error:10.5786261504 Prediction:4.05248
Error:8.19208809087 Prediction:3.6621824
Error:6.34395301757 Prediction:3.318720512
Error:4.91275721681 Prediction:3.01647405056
Error:3.80443918869 Prediction:2.75049716449
Error:2.94615770772 Prediction:2.51643750475
Error:2.28150452886 Prediction:2.31046500418
Error:1.76679710715 Prediction:2.12920920368
Error:1.36820767978 Prediction:1.96970409924
Error:1.05954002722 Prediction:1.82933960733
Error:0.820507797079 Prediction:1.70581885445
Error:0.635401238058 Prediction:1.59712059192
Error:0.492054718752 Prediction:1.50146612089
Error:0.381047174202 Prediction:1.41729018638
Error:0.295082931702 Prediction:1.34321536401
Error:0.22851222231 Prediction:1.27802952033
Error:0.176959864957 Prediction:1.22066597789
Error:0.137037719422 Prediction:1.17018606055
Error:0.106122009921 Prediction:1.12576373328
Error:0.0821808844827 Prediction:1.08667208529
Error:0.0636408769434 Prediction:1.0522714

In [25]:
def neural_network(input, weights):
    out = 0
    for i in range(len(input)):
        out += (input[i] * weights[i])
    return out


def ele_mul(scalar, vector):
    out = [0,0,0]
    for i in range(len(out)):
        out[i] = vector[i] * scalar
    return out

toes = [8.5, 9.5, 9.9, 9.0] 
wlrec = [0.65, 0.8, 0.8, 0.9] 
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]
true = win_or_lose_binary[0]

learning_rate = 0.01
weights = [0.1, 0.2, -.1]
input = [toes[0],wlrec[0],nfans[0]]

for iter in range(3):

    pred = neural_network(input,weights)

    error = (pred - true) ** 2
    delta = pred - true
    weight_deltas = ele_mul(delta,input) # explain error attribution
    
    #delta= -0.14 
    #weight_delta = [8.5 * -0.14, 0.65 * -0.14, 1.2 * -0.14] 
    #weight_delta = [-1.189999999999999, -0.09099999999999994, -0.16799999999999987] INVERSE DIRECTION
    #weights =  [ 0.1 - (0.01 * -1.189999999999999), 0.1 - (0.01 * -0.09099999999999994), 0.1 - (0.01 * -0.167999) ]
    #Weights =  [0.1119, 0.2, -0.1]
    
    print("Iteration:" + str(iter+1))
    print("Pred:" + str(pred))
    print("Error:" + str(error))
    print("Delta:" + str(delta))
    print("Weights:" + str(weights))
    print("Weight_Deltas:")
    print(str(weight_deltas))
    print
   
    for i in range(len(weights)):
        weights[i] -= learning_rate*weight_deltas[i]

Iteration:1
Pred:0.86
Error:0.0196
Delta:-0.14
Weights:[0.1, 0.2, -0.1]
Weight_Deltas:
[-1.189999999999999, -0.09099999999999994, -0.16799999999999987]

Iteration:2
Pred:0.9637575
Error:0.00131351880625
Delta:-0.0362425
Weights:[0.1119, 0.20091, -0.09832]
Weight_Deltas:
[-0.30806125000000056, -0.023557625000000044, -0.04349100000000008]

Iteration:3
Pred:0.990617722813
Error:8.80271252231e-05
Delta:-0.0093822771875
Weights:[0.11498061250000001, 0.20114557625, -0.09788509000000001]
Weight_Deltas:
[-0.07974935609374867, -0.006098480171874899, -0.011258732624999811]



In [39]:
print(0.1 - (0.01 * -1.189999999999999))
print(8.5 * 0.11)
print(0.65 * 0.20)

0.1119
0.935
0.13


In [32]:
toes = [8.5, 9.5, 9.9, 9.0] 
wlrec = [0.65, 0.8, 0.8, 0.9] 
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]
true = win_or_lose_binary[0]

learning_rate = 0.1
weights = [0.1, 0.2, -.1]
input = [toes[0],wlrec[0],nfans[0]]

for iter in range(20):

    pred = np.dot(input,weights)

    error = (pred - true) ** 2
    delta = pred - true
    weight_deltas = np.dot(delta, input) 
    
    #ASK IF IT WILL FIND THE SOLUTION
    weight_deltas[0] = 0 #FIX THE WEIGHT DELTA TO ZERO
    
    
    print("Iteration:" + str(iter+1))
    print("Pred:" + str(pred))
    print("Error:" + str(error))
    print("Delta:" + str(delta))
    print("Weights:" + str(weights))
    print("Weight_Deltas:")
    print(str(weight_deltas))
    print
   
    for i in range(len(weights)):
        weights[i] -= learning_rate*weight_deltas[i]

Iteration:1
Pred:0.86
Error:0.0196
Delta:-0.14
Weights:[0.1, 0.2, -0.1]
Weight_Deltas:
[ 0.    -0.091 -0.168]

Iteration:2
Pred:0.886075
Error:0.012978905625
Delta:-0.113925
Weights:[0.10000000000000001, 0.20910000000000001, -0.083200000000000024]
Weight_Deltas:
[ 0.         -0.07405125 -0.13671   ]

Iteration:3
Pred:0.90729353125
Error:0.00859448934809
Delta:-0.09270646875
Weights:[0.10000000000000001, 0.21650512499999999, -0.069529000000000035]
Weight_Deltas:
[ 0.         -0.0602592  -0.11124776]

Iteration:4
Pred:0.924560111055
Error:0.00569117684408
Delta:-0.0754398889453
Weights:[0.10000000000000001, 0.22253104546874999, -0.058404223750000046]
Weight_Deltas:
[ 0.         -0.04903593 -0.09052787]

Iteration:5
Pred:0.938610790371
Error:0.0037686350589
Delta:-0.0613892096292
Weights:[0.10000000000000001, 0.2274346382501953, -0.049351437076562546]
Weight_Deltas:
[ 0.         -0.03990299 -0.07366705]

Iteration:6
Pred:0.950044530664
Error:0.00249554891656
Delta:-0.0499554693358
Weights

![title](matrixnumber.png)

In [ ]:
#QUIZ
 x * x = 12, 6 * 2
 x * x * x = 12 , 6 * 2 * 1 
 x * x * x * x = 12 , 6 * 2 * 1 * 1
 x * x * x * x * x = 12, 6 * 2 * 1 * 1 * 1
 x * 0 * 0 * x * x * 0 * x * 0 * x * x = 12 , 3 * 2 * 1 * 1 * 2 * 1 * 1 ...

![title](nolinearity.png)

In [87]:
print(2*2*2*2*2*2) 
print(2*32)

64
64


![title](correlation.png)

![title](multilayer2.png)

In [33]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x # returns x if x > 0
# return 0 otherwise

def relu2deriv(output):
    return output>0 # returns 1 for input > 0
# return 0 otherwise

streetlights = np.array( [[ 1, 0, 1 ],
[ 0, 1, 1 ],
[ 0, 0, 1 ],
[ 1, 1, 1 ] ] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

alpha = 0.2
hidden_size = 4
weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

for iteration in xrange(60):
    layer_2_error = 0
    for i in xrange(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        layer_2 = np.dot(layer_1,weights_1_2)  
        
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
        
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
        if(iteration % 10 == 9):
            print "Error:" + str(layer_2_error)
            
    

Error:0.0231722226572
Error:0.376979980889
Error:0.558544634951
Error:0.634231159844
Error:6.58397460375e-05
Error:0.183400147979
Error:0.314970704174
Error:0.358384076763
Error:1.28548071748e-14
Error:0.0327166922284
Error:0.07944050756
Error:0.0830183113303
Error:2.43802511468e-24
Error:0.00161921276342
Error:0.00644823230423
Error:0.0064670549571
Error:0.0
Error:6.29905463671e-05
Error:0.000329266900075
Error:0.000329266900075
Error:0.0
Error:2.85861468972e-06
Error:1.50556226651e-05
Error:1.50556226651e-05
